In [26]:
# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
data = pd.read_csv("insurance.csv")

In [28]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [29]:
data.shape

(1338, 7)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [31]:
data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [32]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [33]:
data.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [34]:
data.duplicated().sum()

np.int64(1)

###Check Categorical Values

In [36]:
data['sex'].unique()

array(['female', 'male'], dtype=object)

In [37]:
data['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [38]:
data['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [39]:
data = pd.get_dummies(data, columns=['sex', 'smoker', 'region'], drop_first=True)

data.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [40]:
data = data.astype({
    'sex_male': int,
    'smoker_yes': int,
    'region_northwest': int,
    'region_southeast': int,
    'region_southwest': int
})

data.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,0,1,0,0,1
1,18,33.770,1,1725.55230,1,0,0,1,0
2,28,33.000,3,4449.46200,1,0,0,1,0
3,33,22.705,0,21984.47061,1,0,1,0,0
4,32,28.880,0,3866.85520,1,0,1,0,0

In [41]:
# Input Features
X = data.drop('charges', axis=1)

# Target Variable
y = data['charges']

In [42]:
X.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,0,1,0,0,1
1,18,33.770,1,1,0,0,1,0
2,28,33.000,3,1,0,0,1,0
3,33,22.705,0,1,0,1,0,0
4,32,28.880,0,1,0,1,0,0

In [43]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [44]:
StandardScaler()

StandardScaler()

###Feature Scaling

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
scaler = StandardScaler()

In [54]:
X = scaler.fit_transform(X)

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [56]:
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)

print("Training Target:", y_train.shape)
print("Testing Target:", y_test.shape)

Training Features: (1070, 8)
Testing Features: (268, 8)
Training Target: (1070,)
Testing Target: (268,)

###Build the ANN

In [67]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Create ANN Model
model = Sequential()

# Input Layer
model.add(Input(shape=(X_train.shape[1],)))

# Hidden Layer 1
model.add(Dense(64, activation='relu'))

# Hidden Layer 2
model.add(Dense(32, activation='relu'))

# Hidden Layer 3
model.add(Dense(16, activation='relu'))

# Output Layer (Regression)
model.add(Dense(1, activation='linear'))

In [68]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                     │ (None, 64)                  │             576 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,201 (12.50 KB)

 Trainable params: 3,201 (12.50 KB)

 Non-trainable params: 0 (0.00 B)

###Compile the ANN

In [69]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

###Train the Model

In [70]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 325459648.0000 - mae: 13518.2432 - val_loss: 310337760.0000 - val_mae: 12654.3477
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 325396224.0000 - mae: 13516.0166 - val_loss: 310234368.0000 - val_mae: 12650.6328
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 325201088.0000 - mae: 13509.5225 - val_loss: 309925696.0000 - val_mae: 12640.1924
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 324664704.0000 - mae: 13492.3672 - val_loss: 309124192.0000 - val_mae: 12614.3496
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 323337600.0000 - mae: 13452.7285 - val_loss: 307329760.0000 - val_mae: 12558.2148
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 320515008.0000 - mae: 13369.5400 - val_loss: 303651904.0000 - val_mae: 12447.3691
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 315252768.0000 - mae: 13214.5352 - val_loss: 297088896.0000 - val_mae: 12253.7559
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 306094240.0000 - mae: 12956.8984 - val_loss: 286533792.0000 - val_mae: 11943.6436
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 291968800.0000 - mae: 12553.1465 - val_loss: 270210880.0000 - val_mae: 11462.0654
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 271618496.0000 - mae: 11960.0459 - val_loss: 247822320.0000 - val_mae: 10786.9102
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 244662176.0000 - mae: 11145.7402 - val_loss: 219399568.0000 - val_mae: 9902.2158
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 211136256.0000 - mae: 10111.6924 - val_loss: 186373168.0000 - val_mae: 8839.5410
Epoch 13/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 174135104.0000 - mae: 8901.2832 - val_loss: 150604256.0000 - val_mae: 7683.4497
Epoch 14/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 136398784.0000 - mae: 7623.6519 - val_loss: 117448056.0000 - val_mae: 6580.4614
Epoch 15/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 104133856.0000 - mae: 6530.1641 - val_loss: 88821112.0000 - val_mae: 5658.3809
Epoch 16/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 79166872.0000 - mae: 5730.4561 - val_loss: 69327168.0000 - val_mae: 5087.1987
Epoch 17/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 62958400.0000 - mae: 5224.8608 - val_loss: 57832456.0000 - val_mae: 4833.0332
Epoch 18/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 53763900.0000 - mae: 5001.7617 - val_loss: 50836164.0000 - val_mae: 4731.9287
Epoch 19/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 48280176.0000 - mae: 4856.0552 - val_loss: 46667460.0000 - val_mae: 4671.9819
Epoch 20/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 44969164.0000 - mae: 4802.6494 - val_loss: 43961020.0000 - val_mae: 4625.4639
Epoch 21/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 42710388.0000 - mae: 4730.0620 - val_loss: 41868048.0000 - val_mae: 4571.4043
Epoch 22/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 41139436.0000 - mae: 4706.6606 - val_loss: 40231112.0000 - val_mae: 4516.9639
Epoch 23/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 39803436.0000 - mae: 4624.5312 - val_loss: 39051920.0000 - val_mae: 4444.2061
Epoch 24/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 38886648.0000 - mae: 4556.1240 - val_loss: 38042528.0000 - val_mae: 4377.6484
Epoch 25/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 38167284.0000 - mae: 4494.3213 - val_loss: 37069088.0000 - val_mae: 4309.2256
Epoch 26/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 37509544.0000 - mae: 4455.0254 - val_loss: 36408164.0000 - val_mae: 4267.6973
Epoch 27/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 37029204.0000 - mae: 4401.9155 - val_loss: 35926840.0000 - val_mae: 4201.2178
Epoch 28/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 36653676.0000 - mae: 4354.9692 - val_loss: 35404612.0000 - val_mae: 4155.0137
Epoch 29/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 36383296.0000 - mae: 4297.8794 - val_loss: 35016752.0000 - val_mae: 4107.6187
Epoch 30/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 36113892.0000 - mae: 4274.8638 - val_loss: 34604732.0000 - val_mae: 4069.5664
Epoch 31/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35875056.0000 - mae: 4249.0757 - val_loss: 34314844.0000 - val_mae: 4040.7468
Epoch 32/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35702068.0000 - mae: 4211.3252 - val_loss: 34124416.0000 - val_mae: 3990.5220
Epoch 33/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35516196.0000 - mae: 4165.7583 - val_loss: 33873996.0000 - val_mae: 3959.2407
Epoch 34/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 35379388.0000 - mae: 4142.8682 - val_loss: 33624640.0000 - val_mae: 3934.2361
Epoch 35/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35253056.0000 - mae: 4132.7588 - val_loss: 33405700.0000 - val_mae: 3924.9956
Epoch 36/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35145564.0000 - mae: 4112.0454 - val_loss: 33346040.0000 - val_mae: 3899.9563
Epoch 37/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35019260.0000 - mae: 4083.8210 - val_loss: 33201486.0000 - val_mae: 3875.1741
Epoch 38/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34949500.0000 - mae: 4050.3276 - val_loss: 33095776.0000 - val_mae: 3855.5466
Epoch 39/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34830420.0000 - mae: 4052.1338 - val_loss: 32909444.0000 - val_mae: 3849.9573
Epoch 40/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34771684.0000 - mae: 4049.0911 - val_loss: 32772542.0000 - val_mae: 3826.7720
Epoch 41/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34698816.0000 - mae: 4017.6936 - val_loss: 32790122.0000 - val_mae: 3805.8357
Epoch 42/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34581488.0000 - mae: 4003.3621 - val_loss: 32619022.0000 - val_mae: 3794.8604
Epoch 43/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34485304.0000 - mae: 3998.4023 - val_loss: 32510428.0000 - val_mae: 3782.9634
Epoch 44/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 34396148.0000 - mae: 3989.1011 - val_loss: 32410942.0000 - val_mae: 3773.3538
Epoch 45/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34349808.0000 - mae: 3983.1902 - val_loss: 32313498.0000 - val_mae: 3756.9133
Epoch 46/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 34255328.0000 - mae: 3965.1658 - val_loss: 32304894.0000 - val_mae: 3746.8545
Epoch 47/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 34159456.0000 - mae: 3948.5286 - val_loss: 32176798.0000 - val_mae: 3740.4087
Epoch 48/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34094828.0000 - mae: 3948.2451 - val_loss: 32108682.0000 - val_mae: 3730.7695
Epoch 49/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34015076.0000 - mae: 3933.5029 - val_loss: 32126634.0000 - val_mae: 3720.1978
Epoch 50/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 33949052.0000 - mae: 3921.6453 - val_loss: 31996936.0000 - val_mae: 3708.1560
Epoch 51/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33871528.0000 - mae: 3922.6729 - val_loss: 31835980.0000 - val_mae: 3709.5762
Epoch 52/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33828128.0000 - mae: 3924.3096 - val_loss: 31751204.0000 - val_mae: 3696.7561
Epoch 53/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 33695588.0000 - mae: 3902.9768 - val_loss: 31773748.0000 - val_mae: 3682.5762
Epoch 54/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33626236.0000 - mae: 3882.1255 - val_loss: 31689370.0000 - val_mae: 3669.6658
Epoch 55/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33559500.0000 - mae: 3887.8271 - val_loss: 31560522.0000 - val_mae: 3671.6052
Epoch 56/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33534596.0000 - mae: 3880.1089 - val_loss: 31526168.0000 - val_mae: 3663.3508
Epoch 57/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 33426126.0000 - mae: 3878.7837 - val_loss: 31479532.0000 - val_mae: 3654.2512
Epoch 58/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33360276.0000 - mae: 3866.3582 - val_loss: 31376154.0000 - val_mae: 3646.5894
Epoch 59/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33266348.0000 - mae: 3858.9272 - val_loss: 31341436.0000 - val_mae: 3638.3091
Epoch 60/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33228268.0000 - mae: 3848.3643 - val_loss: 31354926.0000 - val_mae: 3634.6799
Epoch 61/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 33139972.0000 - mae: 3850.2593 - val_loss: 31235410.0000 - val_mae: 3626.8745
Epoch 62/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33063524.0000 - mae: 3841.4448 - val_loss: 31207462.0000 - val_mae: 3623.8406
Epoch 63/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32993182.0000 - mae: 3825.4639 - val_loss: 31139400.0000 - val_mae: 3610.0608
Epoch 64/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32943742.0000 - mae: 3820.8303 - val_loss: 31030456.0000 - val_mae: 3603.2273
Epoch 65/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 32822540.0000 - mae: 3816.1218 - val_loss: 31031868.0000 - val_mae: 3602.7710
Epoch 66/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32756882.0000 - mae: 3809.0090 - val_loss: 30892610.0000 - val_mae: 3589.7888
Epoch 67/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32701084.0000 - mae: 3804.8589 - val_loss: 30862706.0000 - val_mae: 3585.5786
Epoch 68/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32604286.0000 - mae: 3794.8135 - val_loss: 30817320.0000 - val_mae: 3572.8464
Epoch 69/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32533734.0000 - mae: 3782.8247 - val_loss: 30767486.0000 - val_mae: 3572.0508
Epoch 70/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32518794.0000 - mae: 3772.5649 - val_loss: 30708396.0000 - val_mae: 3567.1580
Epoch 71/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32383394.0000 - mae: 3783.7695 - val_loss: 30641290.0000 - val_mae: 3567.2461
Epoch 72/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32293324.0000 - mae: 3765.7310 - val_loss: 30567962.0000 - val_mae: 3550.5583
Epoch 73/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32229816.0000 - mae: 3759.3501 - val_loss: 30552540.0000 - val_mae: 3543.5281
Epoch 74/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32158606.0000 - mae: 3748.3040 - val_loss: 30472042.0000 - val_mae: 3539.2068
Epoch 75/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 32074082.0000 - mae: 3735.9080 - val_loss: 30493904.0000 - val_mae: 3528.5601
Epoch 76/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31988676.0000 - mae: 3736.5867 - val_loss: 30343664.0000 - val_mae: 3528.5386
Epoch 77/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31894532.0000 - mae: 3731.9773 - val_loss: 30213616.0000 - val_mae: 3519.5491
Epoch 78/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31828934.0000 - mae: 3716.8242 - val_loss: 30198898.0000 - val_mae: 3505.6572
Epoch 79/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31767682.0000 - mae: 3709.3066 - val_loss: 30188406.0000 - val_mae: 3504.5322
Epoch 80/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31666006.0000 - mae: 3710.0225 - val_loss: 30070000.0000 - val_mae: 3500.1216
Epoch 81/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31615342.0000 - mae: 3698.0352 - val_loss: 29947624.0000 - val_mae: 3486.7251
Epoch 82/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31482412.0000 - mae: 3671.8765 - val_loss: 30000704.0000 - val_mae: 3476.8538
Epoch 83/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31430130.0000 - mae: 3675.4534 - val_loss: 29831086.0000 - val_mae: 3483.5015
Epoch 84/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31352966.0000 - mae: 3679.3972 - val_loss: 29764786.0000 - val_mae: 3477.0056
Epoch 85/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31284576.0000 - mae: 3660.3555 - val_loss: 29847320.0000 - val_mae: 3466.4529
Epoch 86/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31172344.0000 - mae: 3650.0068 - val_loss: 29622468.0000 - val_mae: 3460.9434
Epoch 87/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31088132.0000 - mae: 3648.4421 - val_loss: 29552066.0000 - val_mae: 3454.2026
Epoch 88/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31016026.0000 - mae: 3642.4553 - val_loss: 29586826.0000 - val_mae: 3451.6245
Epoch 89/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30883216.0000 - mae: 3628.8762 - val_loss: 29418740.0000 - val_mae: 3448.0203
Epoch 90/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30826536.0000 - mae: 3626.2529 - val_loss: 29370516.0000 - val_mae: 3434.7312
Epoch 91/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30748066.0000 - mae: 3611.0388 - val_loss: 29370340.0000 - val_mae: 3430.3313
Epoch 92/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 30645438.0000 - mae: 3604.4507 - val_loss: 29217910.0000 - val_mae: 3425.0181
Epoch 93/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30578704.0000 - mae: 3609.2996 - val_loss: 29105464.0000 - val_mae: 3420.1741
Epoch 94/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30505890.0000 - mae: 3575.6753 - val_loss: 29103970.0000 - val_mae: 3398.7102
Epoch 95/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 30387512.0000 - mae: 3572.5837 - val_loss: 29006230.0000 - val_mae: 3400.6460
Epoch 96/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30300242.0000 - mae: 3576.9268 - val_loss: 28909924.0000 - val_mae: 3403.7361
Epoch 97/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30239394.0000 - mae: 3562.0571 - val_loss: 28852066.0000 - val_mae: 3384.4431
Epoch 98/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30150610.0000 - mae: 3553.2695 - val_loss: 28758300.0000 - val_mae: 3379.3989
Epoch 99/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30072282.0000 - mae: 3545.7261 - val_loss: 28719374.0000 - val_mae: 3381.1201
Epoch 100/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 29989008.0000 - mae: 3550.8999 - val_loss: 28643584.0000 - val_mae: 3376.3584

In [71]:
y_pred = model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

In [72]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 3572.7522955886193
Mean Squared Error (MSE): 27517422.414016917
R² Score: 0.8227526746943176